---
title: "Data types and structures in R"
author: "Ronny A. Hernández Mora"
date: "21/09/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data types

```{r}
class(5)

class("ceos")

class(FALSE)

class("FALSE")

my_word <- "ceos"
class(my_word)
```


## Data structures

```{r}
my_first_vector <- c(1, 2, 3)
class(my_first_vector)
my_second_vector <- c("a", "b", "c")
class(my_second_vector)

my_third_vector <- c(F, T, F, T)
class(my_third_vector)

FALSE == F

# FALSE == f

f = T

f <- F
```


```{r}
my_list <- list(c(1:5), c("a", "b"))

my_list <- list(first_line <- c(1:5), 
                second_line <- c("a", "b"))


my_list[[1]][2]
```

## Coercion

```{r}
my_mixed_vector <- c(FALSE, TRUE, 3)

my_mixed_vector_2 <- c("w", "t", 5)

example_coercion <- c(1:20, "o", 21:30)

mean(example_coercion)

force_coercion <- as.numeric(example_coercion)
```


```{r}
my_vector_na <- c(NA, NA, NA)
class(my_vector_na)

is.na(my_vector_na)

NA ==  NA

is.na(NA)
```

## Dataframes

```{r}
my_dataframe <- iris

library(visdat)

vis_dat(my_dataframe)
```

```{r}
class(my_dataframe)

class(my_dataframe$Sepal.Length)

library(dplyr)

glimpse(my_dataframe)

# base R
mean(my_dataframe$Sepal.Length)

mean(my_dataframe[, 1])

# tiyverse
my_dataframe %>% 
  select(Sepal.Length) %>% 
  pull() %>% 
  mean()
```

## Factors and dates

```{r}
my_date <- Sys.Date()

class(my_date)

my_other_date <- "2021-09-21"
class(my_other_date)

example <- as.Date(my_other_date)
class(example)

library(lubridate)
check <- ymd(my_other_date)
class(check)

mdy("06-04-2011")

my_factor <- factor(1:3, ordered = TRUE)
```

## Conditional operators

```{r}
library(tictoc)

tic("vector comparison")
a <- 1
b <- 2

a == b

a != b

# %in%

example_vector <- c("alberta", "edmonton", "calgary")
  
"san jose" %in% example_vector  
toc()
```

